"use client";

import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";

const features = [
  {
    title: "AI Design Evaluation",
    desc: "Get detailed feedback on your system design with strengths, weaknesses, and improvements.",
  },
  {
    title: "Follow-up Questions",
    desc: "Practice real interview-style follow-ups dynamically generated by AI.",
  },
  {
    title: "Bottleneck Detection",
    desc: "Identify scalability issues, performance bottlenecks, and system weaknesses instantly.",
  },
  {
    title: "Design Scoring",
    desc: "Get a score based on scalability, reliability, and trade-offs.",
  },
];

export default function Features() {
  return (
    <section className="py-24 px-6 max-w-6xl mx-auto">
      <motion.h2
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-4xl font-bold text-center text-white mb-16"
      >
        Powerful AI System Design Engine
      </motion.h2>

      <div className="grid md:grid-cols-2 gap-8">
        {features.map((feature, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
          >
            <Card className="p-6 rounded-2xl bg-white/10 border border-white/20 backdrop-blur-md transition duration-300 transform hover:-translate-y-2 hover:scale-[1.02] hover:bg-white/20 hover:shadow-[0_0_40px_rgba(99,102,241,0.4)] cursor-pointer">
              <div className="relative">
  
  {/* Glow overlay */}
  <div className="absolute inset-0 rounded-2xl opacity-0 hover:opacity-100 transition duration-300 bg-gradient-to-r from-indigo-500/10 via-cyan-500/10 to-transparent blur-xl" />

  {/* Content */}
  <div className="relative z-10">
    <h3 className="text-xl font-semibold text-white mb-2">
      {feature.title}
    </h3>
    <p className="text-white/70">
      {feature.desc}
    </p>
  </div>

</div>
            </Card>
          </motion.div>
        ))}
      </div>
    </section>
  );
}